[build]
builder = "nixpacks"

[variables]
# Si quieres, puedes colocar tus env aqui, pero no es obligatorio.

[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.openssl",
  "php82Extensions.mbstring",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.curl"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"
